常用:
  - General
  - GameSystem.SinglePlayer
  - GameSystem.DisableTimeout
  - GameSystem.QuickRetry
  - UX.OneKeyEntryEnd
  - UX.OneKeyRetrySkip
  - GameSystem.Window
  - GameSystem.TouchToButtonInput
  - GameSystem.TestProof
  - GameSettings.CreditConfig
  - Utils.MoveAnswerSound

全解和跳过:
  - GameSystem.Unlock
  - Tweaks.TimeSaving.EntryToMusicSelection
  - Tweaks.TimeSaving.ExitToSave
  - Tweaks.TimeSaving.SkipEventInfo
  - Tweaks.TimeSaving.SkipTrackStart
  - Tweaks.TimeSaving.SkipGoodbyeScreen
  - Tweaks.TimeSaving.IWontTapOrSlideVigorously
  - UX.QuickEndPlay
  - GameSystem.AddPlayCountWhenQuickRetry

美化:
  - GameSystem.Assets.Fonts
  - Fancy.CustomLogo
  - Fancy.CustomPlaceName
  - Fancy.CustomVersionString
  - Fancy.CustomCreditsString
  - Fancy.RandomBgm
  - Fancy.CustomSkins
  - Fancy.CustomButton
  - Fancy.DemoMaster
  - Fancy.GamePlay.AlignCircleSlideJudgeDisplay
  - Fancy.GamePlay.SlideArrowAnimation
  - Fancy.GamePlay.SlideFadeInTweak
  - Fancy.GamePlay.SlideLayerReverse
  - UX.FestaControl

实用工具:
  - UX.HideSelfMadeCharts
  - UX.JudgeAccuracyInfo
  - UX.PracticeMode
  - UX.SelectionDetail
  - UX.DisableLightOutGame
  - Fancy.GamePlay.HideHanabi
  - Fancy.GamePlay.JudgeDisplay4B
  - Utils.DisplayTouchInGame
  - UX.FixTrackNumDisplay

系统修改:
  - GameSystem.Window
  - Utils.ScreenPositionAdjust
  - GameSettings.JudgeAdjust
  - GameSystem.Sound
  - GameSystem.CustomCameraId
  - GameSystem.ExteraMouseInput

调试工具:
  - Utils.AntiLag
  - Tweaks.LockFrameRate
  - Tweaks.ResetTouch
  - Utils.DisplayFrameRate
  - Utils.LogUserId
  - Utils.LogNetworkRequests
  - UX.HardwareAlert

键位和灵敏度:
  - GameSystem.AdxHidInput
  - GameSystem.KeyMap
  - GameSettings.TouchSensitivity

高级设置:
  - Fancy.HideMask
  - GameSystem.TouchPanelPort
  - GameSystem.TouchPanelBaudRate
  - GameSystem.SkipBoardNoCheck
  - Fancy.Triggers

过新过热:
  - Fancy.SetFade
  - Fancy.CustomTrackStartDiff
  - Fancy.GamePlay.BreakSlideJudgeBlink
  - Fancy.GamePlay.CustomNoteTypes
  - Fancy.GamePlay.DisableTrackStartTabs
  - Fancy.GamePlay.FanJudgeFlip
  - Fancy.GamePlay.RealisticRandomJudge
  - Fancy.GamePlay.TrackStartProcessTweak
  - Fancy.GamePlay.FixJudgeTouchHoldInNormalArea
  - Fancy.GamePlay.ReviveFinaleVSlide

不建议关闭:
  - UX.ImmediateSave
  - GameSystem.Assets.LoadAssetBundleWithoutManifest
  - GameSystem.Assets.LoadLocalImages
  - GameSystem.Assets.MovieLoader
  - GameSystem.OptionLoadFix
  - Tweaks.SkipUserVersionCheck
  - UX.DontRuinMyAccount
  - UX.Hide1879
  - UX.GrantFinalGateKey
  - Fancy.GamePlay.ExtendNotesPool
  - Tweaks.TimeSaving.SkipStartupWarning
  - Tweaks.TimeSaving.SkipStartupDelays
  - Utils.ShowNetErrorDetail
  - Tweaks.IgnoreAimeServerError
  - UX.NoAmDaemonAlert
  - Utils.ShowErrorLog
  - GameSettings.ForceAsServer
  - GameSystem.RemoveEncryption
